# Generated by Django 4.1.5 on 2023-01-21 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slider_image',
            field=models.ImageField(null=True, upload_to='blogs'),
        ),
    ]
