# Generated by Django 4.1.5 on 2023-01-21 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_category_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='click',
            field=models.IntegerField(default=0),
        ),
    ]
