# Generated by Django 4.1.5 on 2023-01-21 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blog_click'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='pin',
            field=models.BooleanField(default=False),
        ),
    ]
