# Generated by Django 4.1.5 on 2023-01-21 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_subcategory_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='sub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='blog.subcategory'),
        ),
    ]
