# Generated by Django 4.1.5 on 2023-01-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_alter_comment_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='click',
            field=models.IntegerField(default=0, editable=False, null=True),
        ),
    ]
