# Generated by Django 4.1.5 on 2023-02-01 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_contact_created_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
    ]
