# Generated by Django 4.1.5 on 2023-02-06 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_blog_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='slug',
            field=models.SlugField(editable=False, null=True, unique=True),
        ),
    ]
