# Generated by Django 4.1.5 on 2023-02-07 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_instructor_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(blank=True, upload_to='general_settings', verbose_name='logo(138x35)')),
                ('favicon', models.FileField(blank=True, null=True, upload_to='general_settings', verbose_name='favicon(100x100)')),
                ('footer_logo', models.FileField(blank=True, help_text='Saytın aşağısındakı logo', null=True, upload_to='general_settings', verbose_name='Footer logo(150x38)')),
                ('facebook', models.CharField(blank=True, max_length=1500, verbose_name='Facebook')),
                ('linkedin', models.CharField(blank=True, max_length=1500, verbose_name='Linkedin')),
                ('instagram', models.CharField(blank=True, max_length=1500, verbose_name='Instagram')),
                ('twitter', models.CharField(blank=True, max_length=1500, null=True, verbose_name='Twitter')),
            ],
        ),
    ]
