# Generated by Django 4.1.5 on 2023-02-07 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_generalsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='index_top',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Top Basliq Index'),
        ),
    ]
