# Generated by Django 4.1.5 on 2023-02-07 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_generalsettings_index_top'),
    ]

    operations = [
        migrations.RenameField(
            model_name='generalsettings',
            old_name='logo',
            new_name='light_logo',
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='dark_logo',
            field=models.FileField(blank=True, null=True, upload_to='general_settings', verbose_name='logo(138x35)'),
        ),
    ]
