# Generated by Django 4.1.5 on 2023-02-07 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_rename_logo_generalsettings_light_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalsettings',
            name='dark_logo',
            field=models.FileField(blank=True, null=True, upload_to='general_settings', verbose_name='dark logo(138x35)'),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='light_logo',
            field=models.FileField(blank=True, upload_to='general_settings', verbose_name='light logo(138x35)'),
        ),
    ]
